# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 23:01
from __future__ import unicode_literals

import assist_co_server.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=assist_co_server.models.upload_to)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'assistants',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=assist_co_server.models.upload_to)),
                ('date_of_birth', models.DateField()),
                ('primary_assistant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assist_co_server.Assistant')),
            ],
            options={
                'db_table': 'clients',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.SmallIntegerField()),
                ('display', models.CharField(max_length=10)),
                ('permalink', models.CharField(db_index=True, max_length=10)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.SmallIntegerField()),
                ('display', models.CharField(max_length=100)),
                ('permalink', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'professions',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('state', models.CharField(choices=[('ready', 'ready'), ('executing', 'executing'), ('completed', 'completed'), ('terminated', 'terminated')], default='ready', max_length=100)),
                ('completed_on', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('assistant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assist_co_server.Assistant')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assist_co_server.Client')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.SmallIntegerField()),
                ('display', models.CharField(max_length=100)),
                ('permalink', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'task_types',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assist_co_server.TaskType'),
        ),
        migrations.AddField(
            model_name='client',
            name='profession',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assist_co_server.Profession'),
        ),
        migrations.AddField(
            model_name='assistant',
            name='gender',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assist_co_server.Gender'),
        ),
    ]
