# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 23:51
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('assist_co_server', '0003_auto_20161109_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistant',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='assistant',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='updated_at',
            new_name='updated_on',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
