# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist_co_server', '0004_auto_20161109_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='assist_co_server.Gender'),
            preserve_default=False,
        ),
    ]
