# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_co_server', '0009_auto_20161110_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
