# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assist_co_server', '0012_auto_20161130_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='assist_co_server.Client'),
        ),
        migrations.AddField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(null=True, to='assist_co_server.Contact'),
        ),
    ]
