# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assist_co_server', '0013_auto_20161202_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(to='assist_co_server.Contact'),
        ),
    ]
